route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'user@example.com'
    from: 'alerts@example.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'user@example.com'
    auth_identity: 'user@example.com'
    auth_password: 'password'
