version: '3'
services:

  prometheus:
    image: bitnami/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - blackbox
    networks:
      - monitoring
      
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
      
  alertmanager:
    image: bitnami/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml
    ports:
      - "9093:9093"
    depends_on:
      - prometheus
    networks:
      - monitoring
      
  blackbox:
    image: bitnami/blackbox-exporter
    volumes:
      - ./blackbox.yml:/etc/blackbox-exporter/config.yml
    ports:
      - "9115:9115"
    networks:
      - monitoring

networks:
  monitoring:
